<?php declare(strict_types=1);

/*
 * This file is part of ptomulik/icon_bundle_fontawesome.
 *
 * Copyright (c) Paweł Tomulik <ptomulik@meil.pw.edu.pl>
 *
 * View the LICENSE file for full copyright and license information.
 */

use Drupal\icon_bundle_fontawesome\Hooks;

/*
 * This file is part of ptomulik/icon_bundle_fontawesome.
 *
 * Copyright (c) Paweł Tomulik <ptomulik@meil.pw.edu.pl>
 *
 * View the LICENSE file for full copyright and license information.
 */

/**
 * Implements hook_page_attachments().
 */
function icon_bundle_fontawesome_page_attachments(array &$page): void
{
    \Drupal::classResolver(Hooks::class)->pageAttachments($page);
}

/**
 * Implements hook_library_info_alter().
 */
function icon_bundle_fontawesome_library_info_alter(array &$libraries, string $extension): void
{
    \Drupal::classResolver(Hooks::class)->libraryInfoAlter($libraries, $extension);
}

/**
 * Implements hook_theme().
 *
 * @param mixed $existing
 * @param mixed $type
 * @param mixed $theme
 * @param mixed $path
 */
function icon_bundle_fontawesome_theme($existing, $type, $theme, $path): array
{
    return \Drupal::classResolver(Hooks::class)->theme($existing, $type, $theme, $path);
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @param mixed $variables
 */
function icon_bundle_fontawesome_preprocess_fontawesome_icon(&$variables): void
{
    \Drupal::classResolver(Hooks::class)->preprocessFontAwesomeIcon($variables);
}
